### ISSUE TITLE
Add yield optimization

### ISSUE THREAD

**Issue by sthiele** [ARB-Lab/CNApy#55]

**Comment by sthiele** [comment]
@axelvonkamp  I'm having trouble calling this line 105 from `CellNetAnalyzer/code/cnap_methods/yield_optimization.m`
via the octave engine:

https://github.com/ARB-Lab/CNApy/blob/38e192b5bc78a16f199d056a99f12c2fb32a18c8/cnapy/gui_elements/yield_optimization_dialog.py#L219

I get this error:
```
Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/yield_optimization_dialog.py", line 219, in compute
    a = self.eng.eval("[constraints, c_macro]=CNAreadMFNValues(cnap);")
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 493, in eval
    resp = self.feval('evalin', 'base', cmd,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 380, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: get: invalid handle (= nan)
error: called from:
    get_rates at line 28, column 8
    CNAreadMFNValues at line 30, column 5
```
Do you know what the problem might be?

**Comment by axelvonkamp** [comment]
Hi,

 

CNAreadMFNValues(cnap) ist dafür da um die Werte aus der (Matlab) CNA Karte auszulesen, kann also in CNApy weggelassen werden.

 

-Axel

 
 

Gesendet: Mittwoch, 11. November 2020 um 13:57 Uhr
Von: "Sven Thiele" <notifications@github.com>
An: "ARB-Lab/CNApy" <CNApy@noreply.github.com>
Cc: "axelvonkamp" <axelk1@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [ARB-Lab/CNApy] Add yield optimization (#55)


 

@axelvonkamp I'm having trouble calling this line 105 from CellNetAnalyzer/code/cnap_methods/yield_optimization.m
via the octave engine:

https://github.com/ARB-Lab/CNApy/blob/38e192b5bc78a16f199d056a99f12c2fb32a18c8/cnapy/gui_elements/yield_optimization_dialog.py#L219

I get this error:

Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/yield_optimization_dialog.py", line 219, in compute
    a = self.eng.eval("[constraints, c_macro]=CNAreadMFNValues(cnap);")
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 493, in eval
    resp = self.feval('evalin', 'base', cmd,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 380, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: get: invalid handle (= nan)
error: called from:
    get_rates at line 28, column 8
    CNAreadMFNValues at line 30, column 5


Do you know what the problem might be?

**Comment by sthiele** [comment]
Ok, next on
```
a = self.eng.eval(
                "[maxyield,flux_vec,success, status]= CNAoptimizeYield(cnap, c, d, fixedFluxes, c_macro, solver, verbose);", nargout=0)
```
I get:            
```
GLPK is used as LP solver.
warning: Denominator of yield term can become zero.
glp_simplex: unable to recover undefined or non-optimal solution
Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/yield_optimization_dialog.py", line 252, in compute
    a = self.eng.eval(
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 493, in eval
    resp = self.feval('evalin', 'base', cmd,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 380, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: 'getReport' undefined near line 271 column 14
error: called from:
    CNAoptimizeYield at line 271, column 5
```
