### ISSUE TITLE
Integrate MCS computation via duality

### ISSUE THREAD

**Issue by sthiele** [ARB-Lab/CNApy#60]
Basic version is working. This needs the [`cnapy_compute_mcs.m`](https://github.com/SteffKlamt/CellNetAnalyzer/blob/master/code/related/cnapy_compute_mcs.m) from CellNetAnalyzer master.

**Comment by sthiele** [comment]
Under octave `cnapy_compute_mcs.m` returns this error:
```
error: feval: /usr/lib/octave/5.2.0/oct/x86_64-pc-linux-gnu/__init_fltk__.oct: failed to load: libfltk_gl.so.1.3: cannot open shared object file: No such file or directory
error: called from
    graphics_toolkit at line 91 column 5
Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/mcs_dialog.py", line 346, in compute
    nargout=0)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 500, in eval
    plot_res=plot_res)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 382, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: Invalid call to double.  Correct usage is:

 -- double (X)
error: called from:
    print_usage at line 91, column 5
    cnapy_compute_mcs at line 49, column 7
```

**Comment by axelvonkamp** [comment]
Just by looking at it I would guess that 'double.empty' should be replaced by 'zeros'.

**Comment by sthiele** [comment]
@VonAlphaBisZulu What do you think. I'm asking because the `cnapy_compute_mcs.m` is mostly a copy of your `compute_mcs` function:
https://github.com/SteffKlamt/CellNetAnalyzer/blob/master/code/cnap_methods/compute_mcs_dual.m#L524-L526

In general, I think it would be better to avoid such code duplication. :cry: But I don't feel confident to rewrite your function.

**Comment by sthiele** [comment]
Next problematic line is this:
```matlab
r = cell.empty(1,0);
```
Here octave complains as follows:
```
oct2py.utils.Oct2PyError: Octave evaluation error:
error: cell cannot be indexed with .
error: called from:
    cnapy_compute_mcs>findReacAndCoeff at line 202, column 7
    cnapy_compute_mcs>genV at line 160, column 21
    cnapy_compute_mcs at line 53, column 35
```

**Comment by axelvonkamp** [comment]
Try 'cell(1, 0)'

**Comment by axelvonkamp** [comment]
Yes, should be the same.

**Comment by sthiele** [comment]
I put all my changes to ` cnapy_compute_mcs.m` into this branch. 
https://github.com/SteffKlamt/CellNetAnalyzer/compare/sven/octave-fix
There might be more octave compatibility errors that I've not found yet.

**Comment by sthiele** [comment]
@axelvonkamp The mcs calculation under octave is still not working for me. But I don't have cplex and octave on the same computer. Does cplex work with octave? Can you test mcs computation with octave and cplex from the cnapy UI? 
Currently `'intlinprog'` is hard coded here:
https://github.com/ARB-Lab/CNApy/blob/2103ecc359cfb67d6b21ece060ca93f532de7678/cnapy/gui_elements/mcs_dialog.py#L283-L285
You would have to change this to `'java_cplex'` or `'matlab_cplex'`

**Comment by axelvonkamp** [comment]
intlinprog will not work with octave, only 'java_cplex' and 'java_cplex_new' because CPLEX will only work through the Java interface in octave. I can test it, but probably not before Tuesday.

**Comment by sthiele** [comment]
I still get errors. With `java_cplex_new` and with `matlab_cplex` i get:
```
== MCS Computation ==
Verifying that D and T regions are feasible in the original model.
FVA to find blocked reactions in uncompressed model.
#total_reacs: 10, #blocked: 0
Flipped 0 irreversible reactions.
Compressing network.
warning: java2mat is obsolete and will be removed from a future version of Octave
warning: implicit conversion from numeric to char
Verifying D and T region feasibility in compressed model.
FVA to determine model bounds.
FVA to determine model bounds under desired conditions.
#essential: 0 -> 0 more reactions are now non-targetable.
Building CPLEX MILP.
Chosen settings:
  scalar structure containing the fields:

    milp_time_limit =  Inf
    milp_solver = java_cplex_new
    mcs_search_mode =  1
    postproc_verify_mcs = 0
    preproc_compression = 1
    preproc_check_feas = 1
    preproc_D_violations = 0
    milp_bigM = 0
    milp_nullspace = 0
    milp_split_level = 1
    milp_reduce_constraints = 1
    milp_combined_z = 1
    milp_irrev_geq = 1
warning: error caught while executing handle class delete method:
cannot reference properties of class `ConstrainedMinimalCutSetsEnumeratorMILPJ' for non-constructed object

ERROR:  MCS computation failed
        MCS computation failed:

        'cannot reference properties of class `ConstrainedMinimalCutSetsEnumeratorMILPJ' for non-constructed object'

        See command window for details

Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/mcs_dialog.py", line 358, in compute
    self.eng.eval("[mcs] = cnapy_compute_mcs(cnap, genes, maxSolutions, maxSize, milp_time_limit, gKOs, advanced_on, solver, mcs_search_mode, reac_box_vals, dg_T,dg_D);",
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 493, in eval
    resp = self.feval('evalin', 'base', cmd,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 380, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: element number 1 undefined in return list
```
and with `java_cplex`

```
== MCS Computation ==
Verifying that D and T regions are feasible in the original model.
FVA to find blocked reactions in uncompressed model.
#total_reacs: 10, #blocked: 0
Flipped 0 irreversible reactions.
Compressing network.
warning: java2mat is obsolete and will be removed from a future version of Octave
warning: implicit conversion from numeric to char
Verifying D and T region feasibility in compressed model.
FVA to determine model bounds.
FVA to determine model bounds under desired conditions.
#essential: 0 -> 0 more reactions are now non-targetable.
Building CPLEX MILP.
Chosen settings:
  scalar structure containing the fields:

    milp_time_limit =  Inf
    milp_solver = java_cplex
    mcs_search_mode =  1
    postproc_verify_mcs = 0
    preproc_compression = 1
    preproc_check_feas = 1
    preproc_D_violations = 0
    milp_bigM = 0
    milp_nullspace = 0
warning: error caught while executing handle class delete method:
matrix cannot be indexed with .

ERROR:  MCS computation failed
        MCS computation failed:

        'matrix cannot be indexed with .'

        See command window for details

Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/mcs_dialog.py", line 360, in compute
    self.eng.eval("[mcs] = cnapy_compute_mcs(cnap, genes, maxSolutions, maxSize, milp_time_limit, gKOs, advanced_on, solver, mcs_search_mode, reac_box_vals, dg_T,dg_D);",
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 493, in eval
    resp = self.feval('evalin', 'base', cmd,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 380, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: element number 1 undefined in return list
```

**Comment by sthiele** [comment]
I have no `cplex` installed. Wasn't there an option to run it on `òctave` without `cplex`?

**Comment by axelvonkamp** [comment]
There is a new 'glpk' option that can be used as an alternative to 'intlinporg' (the latter is in Matlab only)

**Comment by sthiele** [comment]
> There is a new 'glpk' option that can be used as an alternative to 'intlinporg' (the latter is in Matlab only)

On which CellNetAnalyzer branch does that work?

**Comment by axelvonkamp** [comment]
It should work on octave_compatibility

**Comment by sthiele** [comment]
With
```
self.eng.eval("solver = 'glpk';", nargout=0)
...
self.eng.eval("[mcs] = cnapy_compute_mcs(cnap, genes, maxSolutions, maxSize, milp_time_limit, gKOs, advanced_on, solver, mcs_search_mode, reac_box_vals, dg_T,dg_D);",
                              nargout=0)
```

I get this error:
```
Using MATLAB's MILP solver 'intlinprog'. This version only works with big M and finds one MCS per iteration.
== MCS Computation ==
Verifying that D and T regions are feasible in the original model.
FVA to find blocked reactions in uncompressed model.
#total_reacs: 10, #blocked: 0
Flipped 0 irreversible reactions.
Compressing network.
warning: java2mat is obsolete and will be removed from a future version of Octave
warning: implicit conversion from numeric to char
Verifying D and T region feasibility in compressed model.
FVA to determine model bounds.
FVA to determine model bounds under desired conditions.
#essential: 0 -> 0 more reactions are now non-targetable.
Building MATLAB (intlinprog) MILP.
Chosen settings:
  scalar structure containing the fields:

    milp_time_limit =  Inf
    milp_solver = glpk
    mcs_search_mode =  1
    postproc_verify_mcs = 0
    preproc_compression = 1
    preproc_check_feas = 1
    preproc_D_violations = 0
    milp_bigM =  1000
    milp_nullspace = 0
MILP properties:
  scalar structure containing the fields:

    compressed_stoichiometric_matrix_rows =  4
    compressed_stoichiometric_matrix_columns =  8
    milp_vars =  39
    number_of_equations =  12
    number_of_inequalities =  29
    num_targetable_reactions =  8
    max_Cost =  7
    max_Solutions =  Inf
    time_limit =  Inf
Computing one MCS per iteration -not necessarily with minimum cardinality- with intlinprog MILP solver (bigM formulation).

Step 1: Searching for (not necessarily minimal) cut set.

ERROR:  MCS computation failed
        MCS computation failed:

        ''exitflag' undefined near line 1094 column 88'

        See command window for details

Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/mcs_dialog.py", line 362, in compute
    self.eng.eval("[mcs] = cnapy_compute_mcs(cnap, genes, maxSolutions, maxSize, milp_time_limit, gKOs, advanced_on, solver, mcs_search_mode, reac_box_vals, dg_T,dg_D);",
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 493, in eval
    resp = self.feval('evalin', 'base', cmd,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 380, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: element number 1 undefined in return list
```

**Comment by axelvonkamp** [comment]
Just comment out the warning on line 1094 of CNAMCSEnumerator2 as a quick fix :-)

**Comment by axelvonkamp** [comment]
Just pushed a fix to the octave_compatibility branch.

**Comment by sthiele** [comment]
Ok, I got it working. Let me know when you merge octave_compatibility branch into master.

**Comment by sthiele** [comment]
This works for me now! What do you think? Can we close this Issue?

**Comment by axelvonkamp** [comment]
I currently do not see the possibility to choose between GLPK and CPLEX (cplex_java/cplex_java_new)?

**Comment by sthiele** [comment]
For now this is still disabled because we have not yet a check for CPLEX inplace. I could also add the option to run it anyway but I would prefer to give this option only if CPLEX is working.

**Comment by axelvonkamp** [comment]
I will add functions for querying whether CPLEX Java/Matlab is working to CNA_MEngine.

**Comment by axelvonkamp** [comment]
Just pushed the functions to the CNA_MEngine branch. They need the latest changes from CNA octave_compatibility branch.

**Comment by sthiele** [comment]
@axelvonkamp Shouldn't the cplex checks `eng.is_cplex_matlab_ready()` and `eng.is_cplex_java_ready()` work with octave?
With octave I get this error:
```
Could not find CPLEX installation.
If you want to use CPLEX set 'cplex_root' in 'configure_cplex_paths'.
use octave engine
0
Traceback (most recent call last):
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/cnapy-0.0.1-py3.8.egg/cnapy/gui_elements/mainwindow.py", line 780, in mcs
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/cnapy-0.0.1-py3.8.egg/cnapy/gui_elements/mcs_dialog.py", line 134, in __init__
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/cnapy-0.0.1-py3.8.egg/cnapy/CNA_MEngine.py", line 96, in is_cplex_java_ready
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 729, in __getattr__
    exist = self._exist(name)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.8/site-packages/oct2py/core.py", line 686, in _exist
    raise Oct2PyError(msg % name)
oct2py.utils.Oct2PyError: Value "cplex_java_ready" does not exist in Octave workspace
```

**Comment by axelvonkamp** [comment]
Yes, there is a wrong atrribute name in CNA_MEngine.py, change line 78 to
self.cplex_java_ready= self.eval('cnan.cplex_interface.java;');

**Comment by sthiele** [comment]
@axelvonkamp Ok, mcs with cplex now works for me under octave. I couldn't try matlab as I can't install cplex on the mpi laptop. Maybe you can try mcs with matlab and cplex?

**Comment by axelvonkamp** [comment]
Yes, it is working with Matlab (on Windows), but I don't think it is necessary to offer the CPLEX Java interface when using the Matlab engine. (Actually using the Java-CPLEX interface with Matlab on Linux will crash with the current setup...)

**Comment by sthiele** [comment]
Ok, then I remove the `java_cplex` option.
